"""add_disconnected_at_field

Revision ID: 47a4b13aaa60
Revises: d21d89b27cf9
Create Date: 2025-12-10 23:37:46.590307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a4b13aaa60'
down_revision: Union[str, Sequence[str], None] = 'd21d89b27cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'disconnected_at')
    # ### end Alembic commands ###
